# Generated by Django 5.0.4 on 2024-04-26 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RealEstate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('THB', 'Thai Baht'), ('MMK', 'Myanmar Kyat')], max_length=3)),
                ('street_address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('zipcode', models.CharField(max_length=10)),
                ('area_value', models.DecimalField(decimal_places=4, max_digits=6)),
                ('area_unit', models.CharField(choices=[('sqft', 'Square Feet'), ('acres', 'Acres')], max_length=5)),
                ('rent_or_sale_status', models.CharField(choices=[('rent', 'For Rent'), ('sale', 'For Sale')], max_length=4)),
                ('type', models.CharField(choices=[('apartment', 'Apartment'), ('condo', 'Condo'), ('whole', 'Whole Building')], max_length=20)),
                ('is_available', models.BooleanField()),
                ('available_date', models.DateTimeField(blank=True, null=True)),
                ('no_of_bedrooms', models.PositiveSmallIntegerField()),
                ('no_of_bathrooms', models.PositiveSmallIntegerField()),
                ('is_parking', models.BooleanField()),
                ('facilities', models.TextField()),
                ('nearby_places', models.TextField(blank=True, null=True)),
                ('overview', models.TextField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
