# Generated by Django 5.0.4 on 2024-04-26 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estatequery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestate',
            name='area_value',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
