# Generated by Django 5.0.4 on 2024-04-29 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estatequery', '0003_alter_realestate_no_of_bathrooms_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realestate',
            name='creator',
        ),
        migrations.AddField(
            model_name='realestate',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='realestate',
            name='main_photo',
            field=models.ImageField(null=True, upload_to='estatequery/'),
        ),
        migrations.AddField(
            model_name='realestate',
            name='photo_one',
            field=models.ImageField(null=True, upload_to='estatequery/'),
        ),
        migrations.AddField(
            model_name='realestate',
            name='photo_three',
            field=models.ImageField(null=True, upload_to='estatequery/'),
        ),
        migrations.AddField(
            model_name='realestate',
            name='photo_two',
            field=models.ImageField(null=True, upload_to='estatequery/'),
        ),
        migrations.AddField(
            model_name='realestate',
            name='realtor',
            field=models.EmailField(default='abc', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='realestate',
            name='slug',
            field=models.SlugField(default='abc', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='realestate',
            name='title',
            field=models.CharField(default='abc', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='realestate',
            name='facilities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='is_parking',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='no_of_bathrooms',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='no_of_bedrooms',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='overview',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='type',
            field=models.CharField(choices=[('apartment', 'Apartment'), ('condo', 'Condo'), ('town_house', 'Town House'), ('house', 'House')], max_length=20),
        ),
    ]
