# Generated by Django 5.0.4 on 2024-05-04 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estatequery', '0005_alter_realestate_realtor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestate',
            name='realtor',
            field=models.EmailField(max_length=255),
        ),
    ]
